### ISSUE TITLE
2016 LTSB 问题

### ISSUE THREAD

**Issue by bpplpp** [sharoue/chinawareblock#4]
全家桶一键处理，无限循环 CMD 闪闪闪闪闪闪闪闪闪闪闪闪闪闪闪闪闪闪闪闪闪闪闪闪闪闪闪

**Comment by sharoue** [comment]
虚拟机原版LTSB未能重现，是俄罗斯大神精简的LTSB么？

**Comment by bpplpp** [comment]
原版，不折腾了，谢谢回复。
