### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by daddun** [sharoue/chinawareblock#6]
对百度浏览器无效，提取工具导出的证书也拉黑后也没用。

**Comment by sharoue** [comment]
最近没空。。。为何百毒和360的浏览器都特别突出，我回去研究下。。。

**Comment by sharoue** [comment]
> 对百度浏览器无效，提取工具导出的证书也拉黑后也没用。

百度换了新证书解决，但是360的还是不行。。。

**Comment by yihanwu1024** [comment]
百度和 360 都有好多个证书，这不是 bug，是证书库不全。我有在维护另一个证书库： github.com/yihanwu1024/badcert
