### ISSUE TITLE
部分软件无法导出所有证书

### ISSUE THREAD

**Issue by onlyJinx** [sharoue/chinawareblock#9]
Hello Sharoue，

我尝试用证书导出工具导出时好像无法导出所有证书，有些软件（2345看图王/搜狗浏览器）只能导出一个证书（sha1），还有一个sha256的不会被导出，只有两个都拉黑才能禁止安装，请问这个工具的bug还是我不会操作。。。
![file](https://user-images.githubusercontent.com/21324835/62409484-cb678c80-b60a-11e9-906f-5c8d4d258d57.png)

**Comment by sharoue** [comment]
目前这些脚本确实都只能导出一个证书。。。一直没去学习怎么写个更好的语句出来。比如先枚举每个证书出来然后再精确匹配条件一个一个导出之类的。。。

**Comment by onlyJinx** [comment]
> 目前这些脚本确实都只能导出一个证书。。。一直没去学习怎么写个更好的语句出来。比如先枚举每个证书出来然后再精确匹配条件一个一个导出之类的。。。

OK，谢谢解答～
